import 'package:flutter/material.dart';

class AppInfoScreen extends StatelessWidget {
  const AppInfoScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("App information"),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            children: [
              Text("""
    My Bard is an innovative mobile application that seamlessly integrates Google's AI model, Gemini, using its API to revolutionize the art of storytelling and creativity. With My Bard, users can send requests to its server and receive personalized responses generated by the powerful Gemini AI.
Below are the standout features of My Bard:
    AI-Powered: My Bard harnesses the advanced capabilities of Google's Gemini AI model to craft captivating and personalized responses to user requests. Whether users seek creative prompts, story ideas, or character inspiration, My Bard delivers imaginative and tailored responses in real-time.
    Copy and Save Responses: With My Bard, users can effortlessly copy responses directly from the app interface, enabling quick and convenient access to engaging content. Additionally, users have the option to save responses for future reference by toggling a dedicated button, ensuring that no inspiring idea or story prompt is ever lost.
    Edit and Customize Saved Responses: My Bard empowers users to refine and personalize saved responses according to their preferences. Users can easily edit saved responses, fine-tuning them to better align with their creative vision or storytelling style, fostering a truly interactive and collaborative storytelling experience.
    Share Responses across Platforms: My Bard facilitates seamless sharing of responses across various social media platforms and communication channels. Users can instantly share responses with friends, followers, or writing communities, fostering collaboration and inspiring creativity on a global scale.
    User-Friendly Interface: My Bard boasts an intuitive and user-friendly interface designed to enhance the overall user experience. With streamlined navigation and easy-to-use controls, users can effortlessly navigate the app, explore its features, and engage with AI-generated content with ease.
    My Bard redefines the storytelling experience, offering users a powerful platform to unlock their creative potential and explore the boundless realms of imagination. Whether you're an aspiring writer, creative enthusiast, or simply seeking inspiration, My Bard invites you to embark on a journey of discovery and storytelling excellence. 
Download My Bard today and unleash the magic of AI-powered creativity at your fingertips!
              """),
            ],
          ),
        ),
      ),
    );
  }
}
